### ISSUE TITLE
Bug when using select field with number values

### ISSUE THREAD

**Issue by severila** [yarbshk/vue-formly-buefy#3]
Hi,

there is a bug when using following config:
```
{
  "model": {
    "name": null
  },
  "tabs": [
    {
      "fields": [
        {
          "type": "selection",
          "key": "name",
          "templateOptions": {
            "options": [
              {
                "value": 0,
                "text": "Jesse"
              },
              {
                "value": 3,
                "text": "John"
              },
              {
                "value": 23,
                "text": "Test"
              }
            ]
          }
        }
      ]
    }
  ]
}
```

The issue is when you try to select the first option ("Jesse"). Instead of changing the value of `name` to `0` it changes to `null`. After that it is possible to select "Jesse" again and the value changes correctly to `0`. 

I know that you have written in the docs that the type of "value" should be a String, but Buefy can handle numbers as well, so there seems to be a bug here. From a quick look at the source I'm not sure where this is coming from. Do you have any idea?

Best,
Severin

**Comment by yarbshk** [comment]
hi @severila ! i've enhanced a plugin by [allowing to set zero values for options of the select field](https://github.com/yarbshk/vue-formly-buefy/commit/da5073f88b62312aa7168a83ce9682cf6f08ac46). please upgrade your `package.json` with the following dependency: `"vue-formly-buefy": "^1.0.4"`.

i close the issue. good luck :)

**Comment by severila** [comment]
Thank you very much!
